spring:
   profiles:
       active:
       - dev
---
spring:
    profiles: dev    #开发环境
    application:
            name:microservicecloud-config-deft-dev
---
spring:
    profiles: test    #测试环境
    application:
            name:microservicecloud-config-deft-test